

export enum RolePermission {
  PARTICIPATION_IN_TASKS = 'PARTICIPATION_IN_TASKS',
  MANAGING_TASKS = 'MANAGING_TASKS',
  MANAGING_PARTICIPANTS = 'MANAGING_PARTICIPANTS',
  MANAGING_RELEASES = 'MANAGING_RELEASES'
}